references:
  commands:
    setup_gitconfig: &setup_gitconfig
      name: Setup gitconfig
      command: |
        git config user.email "10177370+mesh1nek0x0@users.noreply.github.com"
        git config user.name "mesh1nek0x0"

version: 2
jobs:
  job-build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  job-test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace

    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  job-release_build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn install
      - run: *setup_gitconfig
      - run: yarn auto-release:${RELEASE_VERSION}

  job-upload_app:
    docker:
      - image: circleci/node:8.10
    steps:
      - run:
          name: "echo tag"
          command: echo $CIRCLE_TAG

workflows:
  version: 2
  ## masterマージ時に実行する
  build_and_test:
    jobs:
      - job-build
      - job-test:
          requires: # buildが成功したら実行する
            - job-build
      - job-upload_app:
          requires: # tagがある場合、およびtestが成功したら実行する
            - job-test
          filters:
            tags:
              only: /^v[0-9](\.[0-9]){2}$/

  ## 特定の日時にrelease向けのbuildを実施する
  release_build:
    triggers:
      - schedule:
          cron: "56 * * * *"
          filters:
            branches:
              only: 
                - master
    jobs:
      - job-release_build

