version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace

    steps:
      - attach_workspace:
          at: .
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: # buildが成功したら実行する
            - build