references:
  commands:
    setup_gitconfig: &setup_gitconfig
      name: Setup gitconfig
      command: |
        git config user.email "10177370+mesh1nek0x0@users.noreply.github.com"
        git config user.name "mesh1nek0x0"

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace

    steps:
      - attach_workspace:
          at: .
      - run: yarn test
      
  patch_release:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn install
      - run: *setup_gitconfig
      - run: yarn auto-release:patch

  minor_release:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn install
      - run: *setup_gitconfig
      - run: yarn auto-release:minor

  major_release:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn install
      - run: *setup_gitconfig
      - run: yarn auto-release:major
  release:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn install
      - run: *setup_gitconfig
      - run: yarn auto-release:${RELEASE_VERSION}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: # buildが成功したら実行する
            - build
